### ISSUE TITLE
Clear a money fieldtype

### ISSUE THREAD

**Issue by remiduval** [duncanmcclean/simple-commerce#459]
### Description

It would be great to be able to clear the SC-specific 'money' fieldtype. At the moment, it gets saved as "£0.00" when cleared.

Use case: I created another 'money' fieldtype on a product page, to show non-premium users the price they'd pay if they were premium. If this field isn't filled in the cp, it shouldn't display a premium price.
I would be cleaner to test against the existence of this field instead of testing against `!= £0.00`

### Environment

Statamic 3.1.34 Pro
Laravel 8.55.0
PHP 8.0.3
4rn0/statamic-v3-image-optimizer 1.0.8
doublethreedigital/simple-commerce 2.3.18
rias/statamic-redirect 1.4.7
roorda-ict/statamic-entries-export 1.0.0

**Comment by duncanmcclean** [comment]
Fixed in c289aac1 - will be in next release.

**Comment by duncanmcclean** [comment]
Tagged in [v2.3.22](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.22)

**Comment by remiduval** [comment]
Sorry to bother with this again - with the new release, it does get cleared and the money field doesn't appear in page content. But somehow, when testing its existence in a template, it returns true and I can also output it as £0.00.

**Comment by duncanmcclean** [comment]
Whoops, that bit should be fixed in the next update.

**Comment by remiduval** [comment]
I think this issue is back:

My Product blueprint has a `price_members` money fieldtype.
Created product "Book", its `price_members` field is clear and doesn't appear in book.md

`{{ if price_members }}` returns `true`
`{{ price_members | dd }}` return `£0.00`

**Comment by duncanmcclean** [comment]
@remiduval This should be fixed in the latest update, [v3.2.17](https://github.com/doublethreedigital/simple-commerce/releases/tag/v3.2.17)

**Comment by remiduval** [comment]
Unfortunately, I still get "£0.00" on a cleared Money fieldtype on v3.2.17

**Comment by duncanmcclean** [comment]
> Unfortunately, I still get "£0.00" on a cleared Money fieldtype on v3.2.17

Is anything saved for the Money field in your product entry? Can you show the code you're using?

**Comment by remiduval** [comment]
Nothing is saved for the Money field `price_members` in the .md file:
[membership.md](https://github.com/duncanmcclean/simple-commerce/files/9396408/membership.md)


But this line returns true: https://github.com/remiduval/apc/blob/5f2d8acc6d7419389ddec9263405c2410363d641/resources/views/components/_entry--product.antlers.html#L50

**Comment by duncanmcclean** [comment]
^ Should be actually fixed now - have even written a test to confirm 🙈

**Comment by remiduval** [comment]
All good now, thank you so much!
